openapi: "3.0.0"
info:
  description: "This is the Authentication API for UC4."
  version: "0.8.2"
  title: "UC4"
servers:
  - url: https://uc4.cs.upb.de/api/authentication-management
tags:
- name: "Version Management"
  description: "Everything about the Version"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"
- name: "Authentication Management"
  description: "Everything about the authentication"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"

paths:
  /version:
    get:
      tags:
      - "Version Management"
      summary: "Get version"
      description: "Returns the version of the current service"
      operationId: "getVersion"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonServiceVersion'
  /users/{username}:
    put:
      tags:
      - "Authentication Management"
      summary: "Changes the password of a user."
      description: "Changes the password of a the user which is authorized."
      operationId: "changePassword"
      parameters:
      - name: "username"
        in: "path"
        required: true
        schema:
          type: "string"
      security:
        - uc4_token_login: []
      requestBody:
        description: "AuthenticationUser with the new password and the same role."
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthUser'
      responses:
        "200":
          description: "OK"
        "400":
          description: | 
            Bad Request  
            types: MalformedLoginToken, Deserialization, JsonValidation, MultipleAuthorizationError
          content:
            application/json:
              schema:
               oneOf:
                  - $ref: '#/components/schemas/GenericError'
                  - $ref: '#/components/schemas/DetailedError'
        "401":
          description: |
            Unauthorized  
            types: JwtAuthorization, LoginTokenExpired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "403":
          description: |
            Forbidden  
            types: OwnerMismatch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "422":
          description: |
            Unprocessable Entity
            types: Validation, PathParameterMismatch, UneditableFields, LoginTokenSignatureInvalid
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GenericError'
                  - $ref: '#/components/schemas/DetailedError'
  /login:
    get:
      tags:
      - "Authentication Management"
      summary: "Retrieve login and refresh token"
      security:
        - uc4_basic: [] 
      description: "Provides the user with login credientals, thereby the user retrieves a login and refresh token as HTTP cookies. All further calls to API use the login token to authenticate the user. The refresh token can be used to request a new login token."
      operationId: "login"
      responses:
        "200":
          description: "OK"
          headers: 
            Set-Cookie:
              schema: 
                type: string
                example: login=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsImV4cCI6MTU5ODYxMzM2NSwidXNlcm5hbWUiOiJhZG1pbiIsImF1dGhlbnRpY2F0aW9uUm9sZSI6IkFkbWluIn0.hb1F2_wql4CwTcLXOPCqE7yRjYH3XL4jomexigKt6OI, Path=/, HttpOnly, Secure, SameSite=Strict; refresh=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyZWZyZXNoIiwiZXhwIjoxNjAwMzQwNzY1LCJ1c2VybmFtZSI6ImFkbWluIiwiYXV0aGVudGljYXRpb25Sb2xlIjoiQWRtaW4ifQ.YGs4XDg95vvN_wkwHGBttoHxkUDxCGkWqqQugOEh0sE0.hb1F2_wql4CwTcLXOPCqE7yRjYH3XL4jomexigKt6OI, Path=/, HttpOnly, Secure, SameSite=Strict;
        "401":
          description: |
            Unauthorized  
            types: BasicAuthorization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
  /login/machine:
    get:
      tags:
      - "Authentication Management"
      summary: "Retrieve login and refresh token in body for machine user authentication"
      security:
        - uc4_basic: [] 
      description: "This endpoint should only be used for machine user authentication, not for a enduser frontend. Please use cookies if possible. Provides the user with login credientals, thereby the user retrieves a login and refresh token in response body. All further calls to API use the login token to authenticate the user. The refresh token can be used to request a new login token."
      operationId: "loginMachineUser"
      responses:
        "200":
          description: "OK"
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/Tokens'
              examples: 
                ExampleTokens:
                  $ref: '#/components/examples/ExampleTokens'
        "401":
          description: |
            Unauthorized  
            types: BasicAuthorization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
  /refresh:
    get:
      tags:
      - "Authentication Management"
      summary: "Retrieve new login token"
      security:
        - uc4_token_refresh_header: []
      description: "Provides the user with a new valid login token. The long lived refresh token is used to request a new short lived login token."
      operationId: "refresh"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonUsername'
          headers: 
            Set-Cookie:
              schema: 
                type: string
                example: login=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsImV4cCI6MTU5ODYxMzM2NSwidXNlcm5hbWUiOiJhZG1pbiIsImF1dGhlbnRpY2F0aW9uUm9sZSI6IkFkbWluIn0.hb1F2_wql4CwTcLXOPCqE7yRjYH3XL4jomexigKt6OI, Path=/, HttpOnly, Secure, SameSite=Strict;
        "400":
          description: |
            Bad Request  
            types: MalformedRefreshToken, MultipleAuthorizationError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "401":
          description: |
            Unauthorized  
            types: JwtAuthorization, RefreshTokenExpired, RefreshTokenMissing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "422":
          description: |
            Unprocessable Entity  
            types: RefreshTokenSignatureInvalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
  /refresh/machine:
    get:
      tags:
      - "Authentication Management"
      summary: "Retrieve new login token in body for machine user authentication"
      security:
        - uc4_token_refresh: []
      description: "This endpoint should only be used for machine user authentication, not for a enduser frontend. Please use cookies if possible. Provides the user with a new valid login token. The long lived refresh token is used to request a new short lived login token."
      operationId: "refreshMachineUser"
      responses:
        "200":
          description: "OK"
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/RefreshToken'
              examples: 
                ExampleTokens:
                  $ref: '#/components/examples/RefreshToken'
        "400":
          description: |
            Bad Request  
            types: MalformedRefreshToken, MultipleAuthorizationError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "401":
          description: |
            Unauthorized  
            types: JwtAuthorization, RefreshTokenExpired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "422":
          description: |
            Unprocessable Entity  
            types: RefreshTokenSignatureInvalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
  /logout:
    get:
      tags:
      - "Authentication Management"
      summary: "Logout user"
      security: [] 
      description: "Invalidate the login and refresh token stored as HTTP cookies. "
      operationId: "logout"
      responses:
        "200":
          description: "OK"

components:
  securitySchemes:
    uc4_basic:
      type: http
      scheme: basic
    uc4_token_login:
      type: apiKey
      in: cookie
      name: login
    uc4_token_refresh:
      type: apiKey
      in: cookie
      name: refresh
    uc4_token_login_header:
      type: http
      scheme: bearer
    uc4_token_refresh_header:
      type: http
      scheme: bearer
  schemas:
    AuthUser:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
        role:
          type: "string"
          enum: ["Admin", "Student", "Lecturer"]
    JsonUsername:
      type: "object"
      properties:
        username:
           type: "string"
    GenericError:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/GenericError'
        - type: object
    DetailedError:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/DetailedError'
        - type: object
    JsonServiceVersion:
      type: object
      properties:
        serviceVersion:
          type: string
    Tokens:
      type: object
      properties:
        login:
          type: "string"
        refresh:
          type: "string"
    RefreshToken:
      type: object
      properties:
        login: 
          type: "string"
        username: 
          type: "string"
  examples:
    ExampleTokens: 
      summary: "Example Tokens"
      value: 
        login: "login=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsImV4cCI6MTU5ODYxMzM2NSwidXNlcm5hbWUiOiJhZG1pbiIsImF1dGhlbnRpY2F0aW9uUm9sZSI6IkFkbWluIn0.hb1F2_wql4CwTcLXOPCqE7yRjYH3XL4jomexigKt6OI"
        refresh: "refresh=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyZWZyZXNoIiwiZXhwIjoxNjAwMzQwNzY1LCJ1c2VybmFtZSI6ImFkbWluIiwiYXV0aGVudGljYXRpb25Sb2xlIjoiQWRtaW4ifQ.YGs4XDg95vvN_wkwHGBttoHxkUDxCGkWqqQugOEh0sE0.hb1F2_wql4CwTcLXOPCqE7yRjYH3XL4jomexigKt6OI"
    RefreshToken:
      summary: "Login Token"
      value:
        login: "login=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsImV4cCI6MTU5ODYxMzM2NSwidXNlcm5hbWUiOiJhZG1pbiIsImF1dGhlbnRpY2F0aW9uUm9sZSI6IkFkbWluIn0.hb1F2_wql4CwTcLXOPCqE7yRjYH3XL4jomexigKt6OI"
        username: "Luke Skywalker"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
