openapi: "3.0.0"
info:
  description: "This is the Authentication API for UC4."
  version: "0.4.1"
  title: "UC4"
servers:
  - url: https://uc4.cs.upb.de/api/authentication-management
tags:
- name: "Version Management"
  description: "Everything about the Version"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"
- name: "Authentication Management"
  description: "Everything about the authentication"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"

paths:
  /version:
    get:
      tags:
      - "Version Management"
      summary: "Get version"
      description: "Returns the version of the current service"
      operationId: "getVersion"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonVersionNumber'
  /users/{username}:
    put:
      tags:
      - "Authentication Management"
      summary: "Changes the password of a user."
      description: "Changes the password of a the user which is authorized."
      operationId: "changePassword"
      parameters:
      - name: "username"
        in: "path"
        required: true
        schema:
          type: "string"
      security:
        - uc4_auth: [] 
      requestBody:
        description: "AuthenticationUser with the new password and the same role."
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthUser'
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        
        "401":
          description: |
            Unauthorized  
            types: authorization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "403":
          description: |
            Forbidden  
            types: not enough privileges
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "422":
          description: |
            Unprocessable Entity  
            types: validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'

components:
  securitySchemes:
    uc4_auth:
      type: http
      scheme: basic
  schemas:
    AuthUser:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
        role:
          type: "string"
          enum: ["Admin", "Student", "Lecturer"]
    Error:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/Error'
        - type: object
    GenericError:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/GenericError'
        - type: object
    DetailedError:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/DetailedError'
        - type: object
    JsonVersionNumber:
      type: object
      properties:
        versionNumber:
          type: string

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"