openapi: "3.0.0"
info:
  description: "This is the Certificate API for UC4."
  version: "0.8.1"
  title: "UC4"

servers:
  - url: https://uc4.cs.upb.de/api/production/certificate-management

tags:
- name: "Version Management"
  description: "Everything about the Version"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"
- name: "Certificate Management"
  description: "Everything about certificates"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"

paths:
  /version:
    get:
      tags:
      - "Version Management"
      summary: "Get version"
      description: "Returns the version of the current service"
      operationId: "getVersion"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonVersionNumber'
  /certificates/{username}:
    post:
      tags:
      - "Certificate Management"
      summary: "Send info to start the certificate creation process"
      description: "Send the CSR, and optionally the encrypted private key, to start the certificate creation process. One can only invoked this process for themselves."
      operationId: "createCertificate"
      security:
        - uc4_token_login: []
        - uc4_token_login_header: []
      parameters:
      - name: "username"
        in: "path"
        description: "Username of the user for which to create a certificate"
        required: true
        schema:
          type: 'string'
      requestBody:
        description: "CSR object that is the base for Certificate Creation"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostMessageCSR'
            examples:
              PostMessageCsrExample:
                $ref: '#/components/examples/PostMessageCsrExample'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonCertificate'
          headers:
            Location:
              schema:
                type: string
                description: "URI of the newly created Certificate"
        "400":
          description: | 
            Bad Request  
            types: MalformedLoginToken, Deserialization, MultipleAuthorizationError, JsonValidation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "401":
          description: |
            Unauthorized  
            types: JwtAuthorization, LoginTokenExpired
          content:
            application/json:  
              schema:
                $ref: '#/components/schemas/GenericError'
        "403":
          description: |
            Forbidden  
            types: OwnerMismatch
          content:
            application/json:  
              schema:
                $ref: '#/components/schemas/GenericError'
        "413":
          description: |
            Payload Too Large  
            types: EntityTooLarge
          content:
            application/json:  
              schema:
                $ref: '#/components/schemas/GenericError'
        "422":
          description: |
            Unprocessable Entity  
            types: Validation, LoginTokenSignatureInvalid
          content:
            application/json: 
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GenericError'
                  - $ref: '#/components/schemas/DetailedError'
                  
  /certificates/{username}/certificate:
    get:
      tags:
      - "Certificate Management"
      summary: "Get a specified certificate"
      description: "Fetch the certificate of the user with the specified username, no authorization required"
      operationId: "getCertificate"
      parameters:
      - name: "username"
        in: "path"
        description: "Username of the user whose certificate is fetched"
        required: true
        schema:
          type: 'string'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonCertificate'
        "404":
            description: |
              Not Found  
              types: KeyNotFound
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/GenericError'
                  
  /certificates/{username}/enrollmentId:
    get:
      tags:
      - "Certificate Management"
      summary: "Get your own enrollment ID"
      description: "Fetch your enrollment ID, specified by the username set in the authorization and in path."
      operationId: "getEnrollmentID"
      security:
        - uc4_token_login: []
        - uc4_token_login_header: []
      parameters:
      - name: "username"
        in: "path"
        description: "Username of the user, of which the enrollmentId is fetched"
        required: true
        schema:
          type: 'string'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonEnrollmentId'
        "400":
          description: | 
            Bad Request  
            types: MalformedLoginToken, MultipleAuthorizationError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "401":
          description: |
            Unauthorized  
            types: JwtAuthorization, LoginTokenExpired
          content:
            application/json:  
              schema:
                $ref: '#/components/schemas/GenericError'
        "422":
          description: |
            Unprocessable Entity  
            types: LoginTokenSignatureInvalid
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/GenericError'
                
  /certificates/{username}/privateKey:
    get:
      tags:
      - "Certificate Management"
      summary: "Fetch the encrypted private key"
      description: "Fetch the encrypted private key of the user with the username specified in path and authorization. One can only fetch their own encrypted private key."
      operationId: "getPrivateKey"
      security:
        - uc4_token_login: []
        - uc4_token_login_header: []
      parameters:
      - name: "username"
        in: "path"
        description: "Username of the user whose private is fetched"
        required: true
        schema:
          type: 'string'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncryptedPrivateKey'
        "400":
          description: | 
            Bad Request  
            types: MalformedLoginToken, MultipleAuthorizationError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "401":
          description: |
            Unauthorized  
            types: JwtAuthorization, LoginTokenExpired
          content:
            application/json:  
              schema:
                $ref: '#/components/schemas/GenericError'
        "403":
          description: |
            Forbidden  
            types: OwnerMismatch
          content:
            application/json:  
              schema:
                $ref: '#/components/schemas/GenericError'
  
components:
  securitySchemes:
    uc4_token_login:
      type: apiKey
      in: cookie
      name: login
    uc4_token_login_header:
      type: http
      scheme: bearer
  schemas:
    EncryptedPrivateKey:
      type: "object"
      properties:
        key:
          type: string
          description: "The encrypted private key."
        iv:
          type: string
          description: "The IV for key encryption/decryption."
        salt:
          type: string
          description: "The salt used to derive the key from the password."
        
    PostMessageCSR:
      type: "object"
      properties:
        certificateSigningRequest:
          type: string
          description: "In PEM format, x509 certificate signing request, as specified in PKCS#10. Common-name must be the enrollmentId."
        encryptedPrivateKey:
          allOf:
            - $ref: "#/components/schemas/EncryptedPrivateKey"
    JsonCertificate:
      type: "object"
      properties:
        certificate:
          type: string
          description: "In PEM format, x509 certificate, as specified in PKCS#10."
    JsonEnrollmentId:
      type: "object"
      properties:
        id:
          type: string
    JsonVersionNumber:
      type: object
      properties:
        versionNumber:
          type: string
    GenericError:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/GenericError'
        - type: object
    DetailedError:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/DetailedError'
        - type: object
        
  examples:
    PostMessageCsrExample:
      summary : "descr"
      value:
        certificateSigningRequest: | 
          -----BEGIN CERTIFICATE REQUEST-----
          MIIChDCCAW4CAQAwETEPMA0GA1UEAxMGdGVzdGlkMIIBIjANBgkqhkiG9w0BAQEF
          AAOCAQ8AMIIBCgKCAQEAsipACqx6inXxSTeiC1sl8PdJXDGQh2MHs7X519XXhMcp
          Aa3XV/9qqt+lYXglGmGb3uHbZ+IGeAkE9Lid6J//Au9ulBnKhKd1Uyy5EqFNLcLm
          6Q4s7kEYWC23xu9GD6EHWJLNn29ywJg801Pl4tLS2LJ45fbfd4QwwTZdrWj1ufNd
          3FVm6XyItw8MI0bfkglsYGqJ3bO7zX41E/23r8iE668smXRGpBfwhtpl1P2AWyBZ
          yXXiKo9aYgDAe2LIz6fO8PZSzWOJLatHDZ1BHlF7k0ZPlABmGekELYyeaola2xS7
          UgO41M8BWJpNmWG9fIiJchFRQCk9gpFFf+zr9I0TzwIDAQABoDAwLgYJKoZIhvcN
          AQkOMSEwHzAdBgNVHQ4EFgQUDq+poSooyuAmOc51K6wd4xUtBtYwCwYJKoZIhvcN
          AQELA4IBAQCPrQ6iF7kbqjT+XijpsK4kMHtCN+2GUsO+/X/GCGN/K74440ZLPEH0
          qQO20o3fc1GDI6ShZ5G//8+m2CItg7WxeFDXc/b6W2c5HqAh6rUvPMIym+9JHaZJ
          aHHNt4N6wWYnZVhvR6Sy+DeDwdog0hQh+FFoDO9bPJF46leN+MdsgTZ8Mwe8liJp
          CTovF8w/FIt197UYT5S/qJ5/zfg5b+KXulQ0zf5LeWng7LvQeywgWdrvsVVmKLM0
          zOUy2PvH59mXlOg78NnoDWWU2Rt1UaVlbOAxOiCuC84j2wIgLEErVS4eYXwHOT+c
          de5esScxXO7Eikl9DwUe3lkqfA1FCjls
          -----END CERTIFICATE REQUEST-----  
        encryptedPrivateKey:
          key: "thisIsAnEncryptedPrivateKey"
          iv: "hbhRVb7R99xsHh3J"
          salt: "this is a salt"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io" 
