openapi: "3.0.0"
info:
  description: "This is the User API for UC4."
  version: "0.4.1"
  title: "UC4"
tags:
- name: "Errors"
  description: "Everything about the user"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"
paths:
  /users:
    get:
      tags:
      - "Errors"
      responses:
        "200":
          description: "Ok"
components:
  schemas:
    Error:
      type: object
      properties:
        name:
          type: string
        detail:
          type: string
      required:
        - code
        - message
    GenericError:
      type: object
      properties:
        type:
          type: string
          enum: [
            "path parameter mismatch", 
            "wrong object",
            "authorization error",
            "not enough privileges",
            "owner mismatch",
            "key not found",
            "key duplicate",
            "teapot"
          ]
        title:
          type: string
      required:
        - code
        - message
    DetailedError:
      type: object
      properties:
        type:
          type: string
          enum: [
            "validation error", 
            "uneditable fields"
          ]
        title:
          type: string
        invalidParams:
          type: array
          items:
            $ref: "#/components/schemas/SimpleError"
      required:
        - code
        - message
    SimpleError:
      type: object
      properties:
        name:
          type: string
        reason:
          type: string
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"