openapi: "3.0.0"
info:
  description: "This is the Error Definition for the UC4 API."
  version: "0.7.1"
  title: "UC4"
tags:
- name: "Errors"
  description: "Unused"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"
paths:
  /unused:
    get:
      tags:
      - "Errors"
      responses:
        "200":
          description: "Ok"
components:
  schemas:
    GenericError:
      type: object
      properties:
        type:
          type: string
          enum: [
            "HLUnprocessableEntity",
            "MalformedRefreshToken",
            "MalformedLoginToken",
            "JwtAuthorization",
            "BasicAuthorization",
            "RefreshTokenExpired",
            "LoginTokenExpired",
            "RefreshTokenSignatureInvalid",
            "LoginTokenSignatureInvalid",
            "PathParameterMismatch",
            "Authorization",
            "NotEnoughPrivileges",
            "OwnerMismatch",
            "KeyNotFound",
            "KeyDuplicate",
            "Deserialization",
            "Teapot",
            "MultipleAuthorizationError",
            "UnsupportedMediaType",
            "EntityTooLarge"
          ]
        title:
          type: string
      required:
        - code
        - message
    InformativeError:
      type: object
      properties:
        type:
          type: string
          enum: [
            "UnexpectedEntity"
          ]
        title:
          type: string
        information:
          type: string
      required:
        - code
        - message
    DetailedError:
      type: object
      properties:
        type:
          type: string
          enum: [
            "Validation", 
            "JsonValidation",
            "UneditableFields",
            "MissingHeader"
          ]
        title:
          type: string
        invalidParams:
          type: array
          items:
            $ref: "#/components/schemas/SimpleError"
      required:
        - code
        - message
    SimpleError:
      type: object
      properties:
        name:
          type: string
        reason:
          type: string
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"