openapi: "3.0.0"
info:
  description: "This is the User API for UC4."
  version: "0.6.2"
  title: "UC4"
tags:
- name: "Errors"
  description: "Everything about the user"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"
paths:
  /users:
    get:
      tags:
      - "Errors"
      responses:
        "200":
          description: "Ok"
components:
  schemas:
    GenericError:
      type: object
      properties:
        type:
          type: string
          enum: [
            "MalformedRefreshToken",
            "MalformedLoginToken",
            "JwtAuthorization",
            "BasicAuthorization",
            "RefreshTokenExpired",
            "LoginTokenExpired",
            "RefreshTokenSignature",
            "LoginTokenSignature",
            "PathParameterMismatch", 
            "UnexpectedEntity",
            "Authorization",
            "NotEnoughPrivileges",
            "OwnerMismatch",
            "KeyNotFound",
            "KeyDuplicate",
            "Teapot"
          ]
        title:
          type: string
      required:
        - code
        - message
    DetailedError:
      type: object
      properties:
        type:
          type: string
          enum: [
            "Validation", 
            "UneditableFields"
          ]
        title:
          type: string
        invalidParams:
          type: array
          items:
            $ref: "#/components/schemas/SimpleError"
      required:
        - code
        - message
    SimpleError:
      type: object
      properties:
        name:
          type: string
        reason:
          type: string
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"