openapi: "3.0.0"
info:
  description: "This is the Hl-Course API for UC4."
  version: "0.5.1"
  title: "UC4"
  
servers:
  - url: https://uc4.cs.upb.de/api/hl-course-management

tags:
- name: "Version Management"
  description: "Everything about the Version"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"
- name: "Course Management"
  description: "Everything about the courses"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"

paths:
  /version:
    get:
      tags:
      - "Version Management"
      summary: "Get version"
      description: "Returns the version of the current service"
      operationId: "getVersion"

      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonVersionNumber'
  /courses:
    post:
      tags:
      - "Course Management"
      summary: "Add a new course to the database"
      description: "Adds a new course to the database after verification. ID field is not used and can be set arbitrarily"
      operationId: "addCourse"
      security:
        - uc4_auth: []
      requestBody:
        description: "Course object that needs to be added to the database"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        "201":
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          headers:
            Location:
              schema:
                type: string
                description: "URI of the newly created course"
        "400":
          description: | 
            Bad Request 
            
            detail contains deserialization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: |
            Unauthorized  
            types: authorization error
          content:
            application/json:  
              schema:
                $ref: '#/components/schemas/GenericError'
        "403":
          description: |
            Forbidden  
            types: not enough privileges, owner mismatch
          content:
            application/json:  
              schema:
                $ref: '#/components/schemas/GenericError'
        "409":
          description: |
            Conflict  
            types: key duplicate
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/GenericError'
        "422":
          description: |
            Unprocessable Entity  
            types: validation error
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/DetailedError'

    get:
      tags:
      - "Course Management"
      summary: "Get all courses"
      security:
        - uc4_auth: [] 
      description: "Returns all courses"
      operationId: "getAllCourses"
      parameters:
      - name: "courseName"
        in: "query"
        description: "Course name to filter by (fuzzy)"
        required: false
        schema:
          type: 'string'
      - name: "lecturerId"
        in: "query"
        description: "LecturerId (username) to filter by"
        required: false
        schema:
          type: 'string'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Course'
        "401":
          description: |
            Unauthorized  
            types: authorization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
  /courses/{id}:
    get:
      tags:
      - "Course Management"
      security:
        - uc4_auth: []
      summary: "Find course by course id"
      description: "Find course by course id"
      operationId: "findCourseByCourseId"
      parameters:
      - name: "id"
        in: "path"
        description: "course id to filter by"
        required: true
        schema:
          type: "string"
      responses:
          "200":
            description: "OK"
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Course'
          "401":
            description: |
              Unauthorized  
              types: authorization error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/GenericError'
          "404":
            description: |
              Not Found  
              types: key not found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/GenericError'
    delete:
      tags:
      - "Course Management"
      summary: "Deletes a course"
      description: ""
      security:
        - uc4_auth: [] 
      operationId: "deleteCourse"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of course to delete"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
        "401":
          description: |
            Unauthorized  
            types: authorization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "403":
          description: |
            Forbidden  
            types: not enough privileges, owner mismatch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "404":
          description: |
            Not Found  
            types: key not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
    put:
      tags:
      - "Course Management"
      summary: "Update an existing course"
      description: ""
      operationId: "updateCourse"
      security:
        - uc4_auth: [] 
      parameters:
      - name: "id"
        in: "path"
        description: "id of course to update"
        required: true
        schema:
          type: "string"
      requestBody:
        description: "Course object that needs to be updated in the database"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        "200":
          description: "OK"
        "400":
          description: | 
            Bad Request 
            
            detail contains deserialization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: |
            Unauthorized  
            types: authorization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "403":
          description: |
            Forbidden  
            types: not enough privileges, owner mismatch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "404":
          description: |
            Not Found  
            types: key not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "422":
          description: |
            Unprocessable Entity  
            types: validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'

components:
  securitySchemes:
    uc4_auth:
      type: http
      scheme: basic
  schemas:
    Course:
      type: "object"
      properties:
        courseId:
          type: string
        courseName:
          type: string
        courseType:
          type: string
          enum: ["Lecture", "Seminar", "Project Group"]
        startDate:
          type: "string"
          format: "date"
        endDate:
          type: "string"
          format: "date"
        ects:
          type: "integer"
          format: "int32"
          minimum: 1
        lecturerId:
          type: "string"
        maxParticipants: 
          type: "integer"
          format: "int32"
          minimum: 1
        currentParticipants: 
          type: "integer"
          format: "int32"
        courseLanguage: 
          type: "string"
          enum: ["German", "English"]
        courseDescription:
          type: "string"
    JsonVersionNumber:
      type: object
      properties:
        versionNumber:
          type: string
    Error:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/Error'
        - type: object
    GenericError:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/GenericError'
        - type: object
    DetailedError:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/DetailedError'
        - type: object
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io" 