openapi: "3.0.0"
info:
  description: "This is the User API for UC4."
  version: "0.4.0"
  title: "UC4"
servers:
  - url: https://uc4.cs.upb.de/api/hyperledger-management
tags:
- name: "Version Management"
  description: "Everything about the Version"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"
paths:
  /version:
    get:
      tags:
      - "Version Management"
      summary: "Get version"
      description: "Returns the version of the current service"
      operationId: "getVersion"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonVersionNumber'
components:
  schemas:
    JsonVersionNumber:
      type: object
      properties:
        versionNumber:
          type: string
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"