openapi: "3.0.0"
info:
  description: "This is the Proposal Definition for the UC4 API."
  version: "0.18.1"
  title: "UC4"
tags:
- name: "Proposals"
  description: "Unused"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"
paths:
  /unused:
    get:
      tags:
      - "Proposals"
      responses:
        "200":
          description: "Ok"
components:
  schemas:
    UnsignedTransaction:
      type: "object"
      properties:
        unsignedTransactionJwt:
          type: string
    SignedTransaction:
      type: "object"
      properties:
        unsignedTransactionJwt:
          type: string
        signature:
          type: string
    UnsignedProposal:
      type: "object"
      properties:
        unsignedProposalJwt:
          type: string
    SignedProposal:
      type: "object"
      properties:
        unsignedProposalJwt:
          type: string
        signature:
          type: string
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
