openapi: "3.0.0"
info:
  description: "This is the Report API for UC4."
  version: "0.14.1"
  title: "UC4"

servers:
  - url: https://uc4.cs.upb.de/api/report-management

tags:
- name: "Version Management"
  description: "Everything about the Version"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"
- name: "Report Management"
  description: "Everything about the Reports"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"

paths:
  /version:
    get:
      tags:
      - "Version Management"
      summary: "Get version"
      description: "Returns the version of the current service"
      operationId: "getVersion"

      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonVersionNumber'

  /reports/{username}/prepare:
    get:
      tags:
      - "Report Management"
      summary: "Prepare a User's report"
      security:
        - uc4_token_login: [] 
        - uc4_token_login_header: []
      description: "Prepare a User's report containing all their data stored in the system, both on chain and in database."
      operationId: "prepareReport"
      parameters:
      - name: "username"
        in: "path"
        description: "The User whose data is requested"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          description: |
            Bad Request    
            types: MalformedLoginToken, MultipleAuthorizationError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "401":
          description: |
            Unauthorized  
            types: JwtAuthorization, LoginTokenExpired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "403":
          description: |
            Forbidden  
            types: NotEnoughPrivileges, OwnerMismatch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "422":
          description: |
            Unprocessable Entity   
            types: LoginTokenSignatureInvalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
  /reports/{username}/result:
    get:
      tags:
      - "Report Management"
      summary: "Get a User's report"
      security:
        - uc4_token_login: [] 
        - uc4_token_login_header: []
      description: "Get a User's report containing all their data stored in the system, both on chain and in database. Needs prepare endpoint to be called at some point before"
      operationId: "getReport"
      parameters:
      - name: "username"
        in: "path"
        description: "The User whose data is requested"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          description: |
            Bad Request    
            types: MalformedLoginToken, MultipleAuthorizationError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "401":
          description: |
            Unauthorized  
            types: JwtAuthorization, LoginTokenExpired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "403":
          description: |
            Forbidden  
            types: NotEnoughPrivileges, OwnerMismatch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        "422":
          description: |
            Unprocessable Entity   
            types: LoginTokenSignatureInvalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
components:
  securitySchemes:
    uc4_token_login:
      type: apiKey
      in: cookie
      name: login
    uc4_token_login_header:
      type: http
      scheme: bearer
  schemas:
    Course:
      type: "object"
      properties:
        courseId:
          type: string
        moduleIds:
          type: array
          items:
            type: string
        courseName:
          type: string
        courseType:
          type: string
          enum: ["Lecture", "Seminar", "Project Group"]
        startDate:
          type: "string"
          format: "date"
        endDate:
          type: "string"
          format: "date"
        ects:
          type: "integer"
          format: "int32"
          minimum: 1
        lecturerId:
          type: "string"
        maxParticipants: 
          type: "integer"
          format: "int32"
          minimum: 1
        currentParticipants: 
          type: "integer"
          format: "int32"
        courseLanguage: 
          type: "string"
          enum: ["German", "English"]
        courseDescription:
          type: "string"
    JsonVersionNumber:
      type: object
      properties:
        versionNumber:
          type: string
    GenericError:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/GenericError'
        - type: object
    DetailedError:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/DetailedError'
        - type: object
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io" 
