urls: 
    - name: CourseAPI
      url: https://raw.githubusercontent.com/upb-uc4/api/develop/course.yaml
    - name: Authentication
      url: https://raw.githubusercontent.com/upb-uc4/api/develop/authentication.yaml