urls: 
    - name: CourseAPI
      url: https://raw.githubusercontent.com/upb-uc4/api/develop/course.yaml
    - name: User-management
      url: https://raw.githubusercontent.com/upb-uc4/api/develop/user-management.yaml