urls: 
    - name: Course-Management
      url: https://raw.githubusercontent.com/upb-uc4/api/develop/course-management.yaml
    - name: User-Management
      url: https://raw.githubusercontent.com/upb-uc4/api/develop/user-management.yaml
    - name: Authentication-Management
      url: https://raw.githubusercontent.com/upb-uc4/api/develop/authentication-management.yaml
    - name: Matriculation-Management
      url: https://raw.githubusercontent.com/upb-uc4/api/develop/matriculation-management.yaml
    - name: Certificate-Management
      url: https://raw.githubusercontent.com/upb-uc4/api/develop/certificate-management.yaml
    - name: Configuration-Management
      url: https://raw.githubusercontent.com/upb-uc4/api/develop/configuration-management.yaml
    - name: Examreg-Management
      url: https://raw.githubusercontent.com/upb-uc4/api/develop/exam-reg-management.yaml
    - name: Admission-Management
      url: https://raw.githubusercontent.com/upb-uc4/api/develop/admission-management.yaml